enhance the sdk of cce addon to support listing addon instances
huaweicloud/golangsdk pull request #428
Opened 2021-04-14 07:59 UTC by Jason-Zhang9309

**What this PR does / why we need it**:

enhance the sdk of cce addon to support listing addon instances

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2021-04-14 12:17 UTC, ShiChangkuo requested changes

2021-04-14 12:17 UTC, ShiChangkuo commented on openstack/cce/v3/addons/urls.go
>  	rbUrl := "https://" + cluster_id + "." + client.ResourceBaseURL()[8:]
this line is hard to understand, suggest to use `net/url` package to generate it.

2021-04-14 12:17 UTC, ShiChangkuo commented on openstack/cce/v3/addons/requests.go
> +	_, r.Err = client.Get(resourceListURL(client, clusterID), &r.Body, &golangsdk.RequestOpts{
dose the RequestOpts is essential？

2021-04-14 12:17 UTC, ShiChangkuo commented on openstack/cce/v3/addons/requests.go
> +		refinedAddons = addons
looks this line is unnecessary.

2021-04-14 12:17 UTC, ShiChangkuo commented on openstack/cce/v3/addons/requests.go
> +				if sVal := GetStructNestedField(&addon, key, value.Driller); !(sVal == value.Value) {
s/`!(sVal == value.Value)`/`sVal != value.Value`/ ?

2021-04-14 12:17 UTC, ShiChangkuo commented on openstack/cce/v3/addons/requests.go
> +					matched = false
missing break?

2021-04-19 03:18 UTC, Jason-Zhang9309 commented on openstack/cce/v3/addons/requests.go
> +				if sVal := GetStructNestedField(&addon, key, value.Driller); !(sVal == value.Value) {
fixed

2021-04-19 03:19 UTC, Jason-Zhang9309 commented on openstack/cce/v3/addons/requests.go
> +					matched = false
fixed

2021-04-19 03:32 UTC, Jason-Zhang9309 commented on openstack/cce/v3/addons/requests.go
> +	_, r.Err = client.Get(resourceListURL(client, clusterID), &r.Body, &golangsdk.RequestOpts{
fixed

2021-04-19 06:59 UTC, Jason-Zhang9309 commented on openstack/cce/v3/addons/urls.go
>  	rbUrl := "https://" + cluster_id + "." + client.ResourceBaseURL()[8:]
fixed

2021-04-20 02:10 UTC, ShiChangkuo approved these changes

2021-04-20 02:11 UTC, merged